const actions = {
  GET_COUNTRIES: "GET_COUNTRIES",
  GET_COUNTRY: "GET_COUNTRY",
  GET_ACTIVITIES: "GET_ACTIVITIES",
  SEARCH_COUNTRIES: "SEARCH_COUNTRIES",
  SET_ORDER: "SET_ORDER",
  SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
  SET_FILTER: "SET_FILTER",
};

export default actions;
